services:
  atmosphere-pi:
    image: atmosphere-pi-imgage
    build:
      context: .
      dockerfile: DevOps/Docker/Dockerfile
      args:                       # passed to the Dockerfile
        UID: "${LOCAL_UID:-1000}"  # Changed from 1001 to 1000
        GID: "${LOCAL_GID:-1000}"  # Changed from 118 to 1000
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"  # Updated to match
    privileged: true
    stdin_open: true  # Keep stdin open for interaction
    tty: true         # Allocate a TTY for interactive Bash
    volumes:
      - ./Software:/workspace/Software
      - ./DevOps/BuildArtifacts:/workspace/BuildArtifacts
    working_dir: /workspace
    environment:
      - CARGO_HOME=/home/appuser/.cargo
      - PATH=/home/appuser/.cargo/bin:$PATH