version: '3.8'
services:
  dev:
    image: pi-dev
    build:
      context: .
      dockerfile: DevOps/Docker/Dockerfile.dev
    privileged: true
    stdin_open: true  # Keep stdin open for interaction
    tty: true         # Allocate a TTY for interactive Bash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Software:/workspace/Software
      - ./DevOps/Docker/Dockerfile.pi3b:/workspace/Dockerfile.pi3b
      - ./DevOps/Ansible:/workspace/Ansible
      - ./DevOps/BuildArtifacts:/workspace/BuildArtifacts
      - ssh-keys:/root/.ssh
    working_dir: /workspace
    entrypoint: >
      /bin/sh -c "
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes &&
      docker buildx create --use &&
      docker buildx inspect --bootstrap &&
      /bin/bash"
volumes:
  ssh-keys: